### ISSUE TITLE
npm run hot issue

### ISSUE THREAD

**Issue by shaurya947** [SRI-SAVE/react-components#1]
After I cloned the repository and ran `npm install`, I tried running `npm run hot`.

I got this error:

``` js
let HtmlWebpackPlugin = require('html-webpack-plugin');
^^^
SyntaxError: Unexpected strict mode reserved word
```

I'm not sure if this is an issue that only I'm facing, but to resolve this, I compiled `webpack.config.js` with babel first, and then ran `npm run hot` (it worked fine).

**Comment by AddictArts** [comment]
Hi @shaurya947 ,

Thanks for asking, that should not have happened. I guess it may be the version of node.js you are using? not sure. I have a 'use strict'; on line 2, hmm. If you have a chance, what version of node? I am using iojs 2.5.0 currently. Thanks for the workaround.

**Comment by shaurya947** [comment]
Node v0.12.7, npm v2.11.3

**Comment by AddictArts** [comment]
Thank you. I added a check and engines to the package.json. For now it needs iojs or node v4. I'm going to close this and there is a workaround.
